services:
  - type: web
    name: bebrand-api
    env: node
    rootDirectory: .
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        value: noreply@bebrand.com
      - key: BREVO_SENDER_NAME
        value: BeBrand
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_CALLBACK_URL
        value: https://be-brand.vercel.app/payment/callback
      - key: FRONTEND_URL
        value: https://be-brand.vercel.app
      - key: BACKEND_URL
        value: https://bebrand-eoo2.onrender.com
      - key: IMAGEKIT_PUBLIC_KEY
        sync: false
      - key: IMAGEKIT_PRIVATE_KEY
        sync: false
      - key: IMAGEKIT_URL
        value: https://ik.imagekit.io/0fxgodyu4

